# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, IConfigurableUI, IDataPreviewer, IExecutable
from tkinter import StringVar
from typing import Any
from typing_extensions import Self
import ttkbootstrap

class PromptReceiverModule(BaseModule, IExecutable, IConfigurableUI, IDataPreviewer):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def on_canvas_load(self: Self, node_id: str) -> Any: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def _handle_prompt_event(self: Self, event_data: Any) -> Any: ...
    def _copy_node_id_to_clipboard(self: Self, node_id: Any) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ttkbootstrap
import tkinter
import tkinter.StringVar
import flowork_kernel
import flowork_kernel.api_contract