# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from bs4 import BeautifulSoup
from flowork_kernel.api_contract import BaseModule, IConfigurableUI, IDataPreviewer, IExecutable
from flowork_kernel.ui_shell import shared_properties
from flowork_kernel.ui_shell.components.LabelledCombobox import LabelledCombobox
from flowork_kernel.utils.payload_helper import get_nested_value
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.ui import WebDriverWait
from tkinter import BooleanVar, IntVar, StringVar, scrolledtext
from typing import Any
from typing_extensions import Self
import json
import os
import re
import time
import ttkbootstrap
import undetected_chromedriver
import urllib.parse

UNDETECTED_CHROME_AVAILABLE = True
UNDETECTED_CHROME_AVAILABLE = False
BS4_AVAILABLE = True
BS4_AVAILABLE = False
SELENIUM_EXTRAS_AVAILABLE = True
SELENIUM_EXTRAS_AVAILABLE = False
class IntelligentContentExtractorModule(BaseModule, IExecutable, IConfigurableUI, IDataPreviewer):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: dict, config: dict, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ttkbootstrap
import tkinter
import tkinter.StringVar
import tkinter.BooleanVar
import tkinter.IntVar
import tkinter.scrolledtext
import os
import time
import re
import json
import urllib
import urllib.parse
import flowork_kernel
import flowork_kernel.api_contract
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.shared_properties
import flowork_kernel.utils
import flowork_kernel.utils.payload_helper
import flowork_kernel.ui_shell.components
import flowork_kernel.ui_shell.components.LabelledCombobox
import undetected_chromedriver
import bs4
import bs4.BeautifulSoup
import selenium
import selenium.webdriver
import selenium.webdriver.common
import selenium.webdriver.common.by
import selenium.webdriver.support
import selenium.webdriver.support.ui
import selenium.webdriver.support.expected_conditions