# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from typing import Any, Callable, Dict
from typing_extensions import Self
import json
import threading

class EventBusService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def publish(self: Self, event_name: str, event_data: Dict[str, Any], publisher_id: str) -> Any: ...
    def subscribe(self: Self, event_name: str, subscriber_id: str, callback: Callable) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import threading
import typing