# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, IConfigurableUI, IDataPreviewer, IExecutable
from flowork_kernel.ui_shell import shared_properties
from typing import Any, Dict
from typing_extensions import Self
import ttkbootstrap

class FailAlwaysPlugin(BaseModule, IExecutable, IConfigurableUI, IDataPreviewer):
    def __init__(self: Self, module_id: str, services: Dict[str, Any]) -> None: ...
    def execute(self: Self, payload: Dict[str, Any], config: Dict[str, Any], status_updater: Any, ui_callback: Any, mode: str) -> Dict[str, Any]: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Dict[str, Any]) -> dict: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...
    def on_install(self: Self) -> Any: ...
    def on_load(self: Self) -> Any: ...
    def on_unload(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract
import typing
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.shared_properties
import ttkbootstrap