[FULL CODE FOR FILE: FLOWORK.vbs]
' Auto-generated by Flowork Installer
' MODIFIED: To add a first-run check and validate the exit code of the debug script.
Set WshShell = CreateObject("WScript.Shell")
scriptPath = WScript.ScriptFullName

Set fso = CreateObject("Scripting.FileSystemObject")
scriptDir = fso.GetParentFolderName(scriptPath)

' --- Define key file names ---
Dim lockFileName, debugScriptName
lockFileName = "teetah.art"
debugScriptName = "DEBUG.bat"

' --- Build full paths ---
Dim lockFilePath, debugScriptPath
lockFilePath = fso.BuildPath(scriptDir, lockFileName)
debugScriptPath = fso.BuildPath(scriptDir, debugScriptName)


' --- Smart Launch Logic ---
If fso.FileExists(lockFilePath) Then
    ' --- NORMAL EXECUTION PATH ---
    ' The teetah.art file exists, so we proceed with the standard silent launch.
    Dim command_normal
    command_normal = "cmd.exe /c ""cd /d " & chr(34) & scriptDir & chr(34) & " && poetry run pythonw pre_launcher.py"""

    ' The '0' hides the window, 'False' to ensure it runs in the background.
    WshShell.Run command_normal, 0, False

Else
    ' --- FIRST RUN / DEBUG PATH ---
    ' The teetah.art file does not exist. We will run the debug/setup script first.

    Dim command_debug, exitCode
    command_debug = chr(34) & debugScriptPath & chr(34)

    ' We run the debug script visibly and wait for it to complete.
    ' The '1' shows the window, 'True' forces the script to wait for it to finish.
    ' (MODIFIED) We now capture the exit code from the script.
    exitCode = WshShell.Run(command_debug, 1, True)

    ' (MODIFIED) We only create the lock file IF the debug script was successful (exit code 0).
    If exitCode = 0 Then
        ' NOTE: After the debug script is done successfully, create the empty lock file
        ' to ensure normal execution on the next run.
        Dim lockFile
        Set lockFile = fso.CreateTextFile(lockFilePath, True)
        lockFile.Close
        Set lockFile = Nothing
    Else
        ' NOTE: If the script failed, we inform the user and do NOT create the lock file.
        WScript.Echo "First-time setup (DEBUG.bat) failed. The lock file 'teetah.art' was not created. Please check the console for errors. The setup will run again next time."
    End If

End If


' Clean up objects
Set fso = Nothing
Set WshShell = Nothing