' Auto-generated by Flowork Installer
Set WshShell = CreateObject("WScript.Shell")
scriptPath = WScript.ScriptFullName
Set fso = CreateObject("Scripting.FileSystemObject")
scriptDir = fso.GetParentFolderName(scriptPath)
python_exe = chr(34) & scriptDir & "\python\pythonw.exe" & chr(34)
' (FIXED) Point to the .pyw file to ensure a completely silent launch on Windows
script_to_run = chr(34) & scriptDir & "\pre_launcher.pyw" & chr(34)
command = python_exe & " " & script_to_run
WshShell.Run command, 0, False