
' Auto-generated by Flowork Installer
' MODIFIED: To add a first-run check for a lock file (teetah.art).

Set WshShell = CreateObject("WScript.Shell")
scriptPath = WScript.ScriptFullName

Set fso = CreateObject("Scripting.FileSystemObject")
scriptDir = fso.GetParentFolderName(scriptPath)

' --- Define key file names ---
' NOTE: These are the files checked/run by this launcher.
Dim lockFileName, debugScriptName
lockFileName = "teetah.art"
debugScriptName = "DEBUG.bat"

' --- Build full paths ---
' NOTE: Constructing full paths to avoid ambiguity.
Dim lockFilePath, debugScriptPath
lockFilePath = fso.BuildPath(scriptDir, lockFileName)
debugScriptPath = fso.BuildPath(scriptDir, debugScriptName)


' --- Smart Launch Logic ---
' NOTE: Check if the lock file exists to determine if this is the first run.

If fso.FileExists(lockFilePath) Then
    ' --- NORMAL EXECUTION PATH ---
    ' NOTE: The AO.LA file exists, so we proceed with the standard silent launch.
    ' We use 'poetry run' to execute the script within its virtual environment.
    Dim command_normal
    command_normal = "cmd.exe /c ""cd /d " & chr(34) & scriptDir & chr(34) & " && poetry run pythonw pre_launcher.py"""

    ' NOTE: The '0' hides the window, 'False' to ensure it runs in the background.
    WshShell.Run command_normal, 0, False

Else
    ' --- FIRST RUN / DEBUG PATH ---
    ' NOTE: The teetah.art file does not exist. We will run the debug/setup script first.

    Dim command_debug
    command_debug = chr(34) & debugScriptPath & chr(34)

    ' NOTE: We run the debug script visibly and wait for it to complete.
    ' The '1' shows the window, 'True' forces the script to wait for it to finish.
    WshShell.Run command_debug, 1, True

    ' NOTE: After the debug script is done, create the empty lock file
    ' to ensure normal execution on the next run.
    Dim lockFile
    Set lockFile = fso.CreateTextFile(lockFilePath, True)
    lockFile.Close
    Set lockFile = Nothing

End If


' Clean up objects
Set fso = Nothing
Set WshShell = Nothing
