# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import os
import platform
import shutil
import signal
import subprocess
import sys
import time
import zipfile

PYTHON_ZIP_NAME = 'python.zip'
PYTHON_DIR_NAME = 'python'
MAIN_SCRIPT_BASE_NAME = 'main'
PRELOADER_PID_FILE = 'pre_launcher.pid'
child_process = None
def show_progress(message: Any) -> Any:
    ...

def extract_archive(zip_name: Any, target_dir: Any, project_root: Any) -> Any:
    ...

def find_main_script(project_root: Any) -> Any:
    ...

def signal_handler(sig: Any, frame: Any) -> Any:
    ...

def main() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import os
import zipfile
import subprocess
import time
import shutil
import platform
import signal
import ntpath
import json
import ast
import re
import flowork_kernel
import flowork_kernel.api_contract
import ttkbootstrap
import tkinter
import tkinter.scrolledtext
import tkinter.BooleanVar
import tkinter.messagebox
import importlib
import inspect
import threading
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.custom_widgets
import flowork_kernel.ui_shell.custom_widgets.scrolled_frame
import collections
import collections.OrderedDict
import tkinter.Text
import queue