# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from tkinter import ttk
from typing import Any
from typing_extensions import Self
import os
import subprocess
import sys
import threading
import time
import tkinter
import traceback

DEV_MODE_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAysqZG2+F82W0TgLHmF3Y\n0GRPEZvXvmndTY84N/wA1ljt+JxMBVsmcVTkv8f1TrmFRD19IDzl2Yzb2lgqEbEy\nGFxHhudC28leDsVEIp8B+oYWVm8Mh242YKYK8r5DAvr9CPQivnIjZ4BWgKKddMTd\nharVxLF2CoSoTs00xWKd6VlXfoW9wdBvoDVifL+hCMepgLLdQQE4HbamPDJ3bpra\npCgcAD5urmVoJEUJdjd+Iic27RBK7jD1dWDO2MASMh/0IyXyM8i7RDymQ88gZier\nU0OdWzeCWGyl4EquvR8lj5GNz4vg2f+oEY7h9AIC1f4ARtoihc+apSntqz7nAqa/\nsQIDAQAB\n-----END PUBLIC KEY-----'
class PreloaderWindow:
    def __init__(self: Self) -> None: ...
    def update_status(self: Self, text: Any) -> Any: ...

def _validate_dev_mode() -> Any:
    ...

def run_background_processes(window_instance: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import tkinter
import tkinter.ttk
import threading
import subprocess
import os
import sys
import time
import traceback
import ntpath
import json
import ast
import re
import flowork_kernel
import flowork_kernel.api_contract
import ttkbootstrap
import tkinter.scrolledtext
import tkinter.BooleanVar
import tkinter.messagebox
import importlib
import inspect
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.custom_widgets
import flowork_kernel.ui_shell.custom_widgets.scrolled_frame
import collections
import collections.OrderedDict
import tkinter.Text
import queue