# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from contextlib import contextmanager
from typing import Any
from typing_extensions import Self
import os
import sqlite3

class DatabaseService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def _initialize_database(self: Self) -> Any: ...
    def get_connection(self: Self) -> Any: ...
    def _dict_factory(self: Self, cursor: Any, row: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sqlite3
import os
import contextlib
import ntpath