# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseTriggerListener
from typing import Any
from typing_extensions import Self

class EventBusListener(BaseTriggerListener):
    def __init__(self: Self, trigger_id: str, config: dict, services: dict) -> None: ...
    def start(self: Self) -> Any: ...
    def stop(self: Self) -> Any: ...
    def _handle_internal_event(self: Self, event_data_from_bus: dict) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract