# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseUIProvider
from flowork_kernel.utils.performance_logger import log_performance
from tkinter import Menu
from typing import Any
from typing_extensions import Self
import webbrowser

class MenubarManager:
    def __init__(self: Self, main_window: Any, kernel: Any) -> None: ...
    def _logout(self: Self) -> Any: ...
    def build_menu(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import tkinter
import tkinter.Menu
import flowork_kernel
import flowork_kernel.api_contract
import flowork_kernel.utils
import flowork_kernel.utils.performance_logger
import webbrowser