# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from flowork_kernel.exceptions import PermissionDeniedError
from typing import Any
from typing_extensions import Self
import base64
import hashlib
import json
import os

class PermissionManagerService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def load_rules_from_source(self: Self, rules_dict: Any) -> Any: ...
    def check_permission(self: Self, capability: str, is_system_call: bool) -> bool: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import json
import base64
import flowork_kernel
import flowork_kernel.exceptions
import hashlib