# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from datetime import datetime, timedelta
from flowork_kernel.api_client import ApiClient
from typing import Any
from typing_extensions import Self
import base64
import hashlib
import json
import os
import requests
import shutil
import tempfile
import uuid
import zipfile

class CommunityAddonService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def _load_core_component_ids(self: Self) -> Any: ...
    def upload_component(self: Self, comp_type: Any, component_id: Any, description: Any, tier: Any) -> Any: ...
    def upload_model(self: Self, model_filepath: str, model_id: str, description: str, tier: str) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import tempfile
import zipfile
import shutil
import base64
import requests
import json
import uuid
import datetime
import hashlib
import flowork_kernel
import flowork_kernel.api_client
import ntpath