# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from typing import Any
from typing_extensions import Self
import json
import os
import re
import threading
import time

class AgentExecutorService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def run_dynamic_agent_synchronous(self: Self, initial_payload: dict, full_prompt_template: str, connected_tools: list, ai_brain_endpoint: str, status_updater: Any, agent_display_updater: Any, agent_tool_highlighter: Any) -> Any: ...
    def _get_tools_prompt_from_nodes(self: Self, tool_nodes: list) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import threading
import json
import time
import re
import os