# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseDashboardWidget
from flowork_kernel.core import build_security
from tkinter import Text, ttk
from typing import Any
from typing_extensions import Self
import datetime
import ttkbootstrap

class LogViewerWidget(BaseDashboardWidget):
    def __init__(self: Self, parent: Any, coordinator_tab: Any, kernel: Any, widget_id: str) -> None: ...
    def on_widget_load(self: Self) -> Any: ...
    def on_widget_destroy(self: Self) -> Any: ...
    def _create_widgets(self: Self) -> Any: ...
    def copy_log_to_clipboard(self: Self) -> Any: ...
    def clear_log(self: Self, feedback: Any) -> Any: ...
    def write_to_log(self: Self, message: Any, level: Any) -> Any: ...
    def _filter_logs(self: Self, event: Any) -> Any: ...

_UNUSED_SIGNATURE = 'B3Ba%m#rDeKa'
_UNUSED_SIGNATURE = 'B3Ba%m#rDeKa'
_UNUSED_SIGNATURE = 'B3Ba%m#rDeKa'

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.core
import flowork_kernel.core.build_security
import ttkbootstrap
import tkinter
import tkinter.Text
import tkinter.ttk
import datetime
import flowork_kernel.api_contract