# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from bs4 import BeautifulSoup
from flowork_kernel.api_contract import BaseModule, IConfigurableUI, IDataPreviewer, IExecutable
from flowork_kernel.ui_shell import shared_properties
from flowork_kernel.ui_shell.components.LabelledCombobox import LabelledCombobox
from flowork_kernel.ui_shell.custom_widgets.tooltip import ToolTip
from flowork_kernel.utils.payload_helper import get_nested_value
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from tkinter import BooleanVar, IntVar, StringVar, scrolledtext
from typing import Any
from typing_extensions import Self
from webdriver_manager.chrome import ChromeDriverManager
import hashlib
import json
import os
import re
import time
import ttkbootstrap

SELENIUM_AVAILABLE = True
SELENIUM_AVAILABLE = False
class AdvancedWebScraperModule(BaseModule, IExecutable, IConfigurableUI, IDataPreviewer):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: dict, config: dict, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...
    def get_dynamic_output_schema(self: Self, config: Any) -> Any: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import time
import re
import json
import hashlib
import bs4
import bs4.BeautifulSoup
import flowork_kernel
import flowork_kernel.api_contract
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.shared_properties
import flowork_kernel.utils
import flowork_kernel.utils.payload_helper
import ttkbootstrap
import tkinter
import tkinter.scrolledtext
import tkinter.StringVar
import tkinter.BooleanVar
import tkinter.IntVar
import flowork_kernel.ui_shell.custom_widgets
import flowork_kernel.ui_shell.custom_widgets.tooltip
import flowork_kernel.ui_shell.components
import flowork_kernel.ui_shell.components.LabelledCombobox
import selenium
import selenium.webdriver
import selenium.webdriver.chrome
import selenium.webdriver.chrome.service
import webdriver_manager
import webdriver_manager.chrome
import ntpath
import flowork_kernel.ui_shell.components.InfoLabel
import transformers
import transformers.pipeline
import llama_cpp
import llama_cpp.Llama
import base64
import imaplib
import email
import email.header
import smtplib
import email.mime
import email.mime.text
import email.mime.multipart
import pandas
import flowork_kernel.exceptions
import tkinter.filedialog
import openpyxl
import openpyxl.load_workbook
import typing
import flowork_kernel.ui_shell.components.PropertyField
import flowork_kernel.ui_shell.components.Separator
import flowork_kernel.utils.condition_evaluator
import PIL
import PIL.Image
import PIL.ImageTk
import urllib
import urllib.parse
import undetected_chromedriver
import selenium.webdriver.common
import selenium.webdriver.common.by
import selenium.webdriver.support
import selenium.webdriver.support.ui
import selenium.webdriver.support.expected_conditions
import threading
import flowork_kernel.api_client
import tkinter.Text
import tkinter.DoubleVar
import flowork_kernel.utils.file_helper
import shutil