# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule
from tkinter import scrolledtext
from typing import Any
from typing_extensions import Self
import json
import ttkbootstrap

class DebugPopupModule(BaseModule):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def _show_popup_on_ui_thread(self: Self, module_instance: Any, title: Any, data_string: Any) -> Any: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract
import json
import ttkbootstrap
import tkinter
import tkinter.scrolledtext