# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.exceptions import PermissionDeniedError
from flowork_kernel.kernel import Kernel
from typing import Any
from typing_extensions import Self
import sys

_kernel_instance = None
def get_kernel() -> Any:
    ...

class PermissionHook:
    def __init__(self: Self) -> None: ...
    def activate(self: Self, event_data: Any) -> Any: ...
    def find_spec(self: Self, fullname: Any, path: Any, target: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import flowork_kernel
import flowork_kernel.kernel
import flowork_kernel.exceptions