# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self
import google.generativeai

class GeminiConnection:
    def __init__(self: Self, kernel: Any) -> None: ...
    def configure(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import google
import google.generativeai