# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from typing import Any
from typing_extensions import Self
import hashlib
import json
import os
import re
import subprocess
import sys
import time

class AutoCompilerService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def _check_nuitka(self: Self) -> Any: ...
    def start(self: Self) -> Any: ...
    def initial_scan(self: Self) -> Any: ...
    def _compile_if_needed(self: Self, component_path: Any, component_id: Any) -> Any: ...
    def _calculate_fingerprint(self: Self, component_path: Any, source_py_path: Any) -> Any: ...
    def _run_nuitka_compilation(self: Self, source_py_path: Any, component_id: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import subprocess
import json
import hashlib
import time
import re
import nuitka
import ntpath