# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from apscheduler.jobstores.base import JobLookupError
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from base_service import BaseService
from datetime import datetime
from typing import Any
from typing_extensions import Self

class SchedulerManagerService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def start(self: Self) -> Any: ...
    def stop(self: Self) -> Any: ...
    def schedule_rule(self: Self, rule_id: Any, rule_data: Any) -> Any: ...
    def remove_scheduled_rule(self: Self, rule_id: Any) -> Any: ...
    def get_next_run_time(self: Self, job_id: str) -> datetime | None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import apscheduler
import apscheduler.schedulers
import apscheduler.schedulers.background
import apscheduler.triggers
import apscheduler.triggers.cron
import apscheduler.triggers.cron.CronTrigger
import apscheduler.jobstores
import apscheduler.jobstores.base
import datetime