# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseDashboardWidget
from flowork_kernel.core import build_security
from tkinter import StringVar, messagebox, scrolledtext
from typing import Any
from typing_extensions import Self
import ttkbootstrap

class PromptSenderWidget(BaseDashboardWidget):
    def __init__(self: Self, parent: Any, coordinator_tab: Any, kernel: Any, widget_id: str) -> None: ...
    def _send_prompt(self: Self) -> Any: ...

_UNUSED_SIGNATURE = 'B3Ba%m#rDeKa'

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.core
import flowork_kernel.core.build_security
import ttkbootstrap
import tkinter
import tkinter.StringVar
import tkinter.scrolledtext
import tkinter.messagebox
import flowork_kernel.api_contract