# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, BaseUIProvider
from plugins.flowork_core_ui.ai_architect_page import AiArchitectPage
from plugins.flowork_core_ui.ai_trainer_page import AITrainerPage
from plugins.flowork_core_ui.core_editor_page import CoreEditorPage
from plugins.flowork_core_ui.generator_page import GeneratorPage
from plugins.flowork_core_ui.marketplace_page import MarketplacePage
from plugins.flowork_core_ui.model_converter_page import ModelConverterPage
from plugins.flowork_core_ui.pricing_page import PricingPage
from plugins.flowork_core_ui.prompt_manager_page import PromptManagerPage
from plugins.flowork_core_ui.settings_tab import SettingsTab
from plugins.flowork_core_ui.template_manager_page import TemplateManagerPage
from plugins.flowork_core_ui.trigger_manager_page import TriggerManagerPage
from scanners.diagnostics_page import DiagnosticsPage
from typing import Any
from typing_extensions import Self

class CoreUIProvider(BaseModule, BaseUIProvider):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def get_ui_tabs(self: Self) -> Any: ...
    def get_menu_items(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract
import plugins
import plugins.flowork_core_ui
import plugins.flowork_core_ui.settings_tab
import plugins.flowork_core_ui.template_manager_page
import plugins.flowork_core_ui.generator_page
import plugins.flowork_core_ui.trigger_manager_page
import plugins.flowork_core_ui.marketplace_page
import plugins.flowork_core_ui.ai_architect_page
import plugins.flowork_core_ui.core_editor_page
import plugins.flowork_core_ui.pricing_page
import plugins.flowork_core_ui.ai_trainer_page
import plugins.flowork_core_ui.model_converter_page
import plugins.flowork_core_ui.prompt_manager_page
import scanners
import scanners.diagnostics_page