# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from flowork_kernel.api_contract import BaseTriggerListener
from importlib.machinery import ExtensionFileLoader
from typing import Any
from typing_extensions import Self
import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import uuid
import zipfile

class TriggerManagerService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def start(self: Self) -> Any: ...
    def _is_cache_valid(self: Self) -> Any: ...
    def discover_and_load_triggers(self: Self) -> Any: ...
    def _process_single_trigger(self: Self, trigger_dir: Any, trigger_id: Any, manifest_override: Any) -> Any: ...
    def _calculate_requirements_hash(self: Self, file_path: Any) -> Any: ...
    def _install_dependencies_locally(self: Self, component_path: Any, component_name: Any) -> Any: ...
    def get_config_ui_class(self: Self, trigger_id: str) -> Any: ...
    def start_all_listeners(self: Self, event_data: Any) -> Any: ...
    def stop_all_listeners(self: Self) -> Any: ...
    def _handle_event(self: Self, event_data: dict) -> Any: ...
    def install_component(self: Self, zip_filepath: str) -> (bool, str): ...
    def uninstall_component(self: Self, component_id: str) -> (bool, str): ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import json
import importlib
import importlib.util
import importlib.machinery
import uuid
import time
import tempfile
import zipfile
import shutil
import flowork_kernel
import flowork_kernel.api_contract
import hashlib
import subprocess
import sys
import ntpath