# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from diagnostics_page import DiagnosticsPage
from flowork_kernel.api_contract import BaseModule, BaseUIProvider
from scanners.base_scanner import BaseScanner
from tkinter import Text, messagebox, scrolledtext
from typing import Any
from typing_extensions import Self
import importlib
import inspect
import json
import os
import queue
import re
import threading
import time
import ttkbootstrap

class SystemDiagnosticsUIProvider(BaseUIProvider, BaseModule):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def get_ui_tabs(self: Self) -> Any: ...
    def get_menu_items(self: Self) -> Any: ...
    def scan_single_component_and_get_status(self: Self, component_path: str) -> (bool, str): ...
    def _discover_scanners(self: Self) -> Any: ...
    def start_scan_headless(self: Self, scan_id: str, target_scanner_id: str) -> dict: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ttkbootstrap
import tkinter
import tkinter.Text
import tkinter.scrolledtext
import tkinter.messagebox
import threading
import time
import queue
import os
import re
import json
import importlib
import inspect
import flowork_kernel
import flowork_kernel.api_contract
import ntpath