# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, IConfigurableUI, IDataPreviewer, IExecutable
from flowork_kernel.ui_shell import shared_properties
from flowork_kernel.ui_shell.components.LabelledCombobox import LabelledCombobox
from flowork_kernel.utils.payload_helper import get_nested_value
from tkinter import StringVar
from typing import Any
from typing_extensions import Self
import base64
import ttkbootstrap

class DecodeBase64Text1998Module(BaseModule, IExecutable, IConfigurableUI, IDataPreviewer):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: dict, config: dict, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...
    def get_dynamic_output_schema(self: Self, config: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.shared_properties
import flowork_kernel.utils
import flowork_kernel.utils.payload_helper
import flowork_kernel.ui_shell.components
import flowork_kernel.ui_shell.components.LabelledCombobox
import ttkbootstrap
import tkinter
import tkinter.StringVar
import base64