# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, IConfigurableUI, IDataPreviewer, IExecutable
from tkinter import StringVar, Text, filedialog
from typing import Any
from typing_extensions import Self
import json
import ttkbootstrap

class SetVariableModule(BaseModule, IExecutable, IConfigurableUI, IDataPreviewer):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def get_dynamic_output_schema(self: Self, config: Any) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import flowork_kernel
import flowork_kernel.api_contract
import json
import ttkbootstrap
import tkinter
import tkinter.scrolledtext
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.shared_properties
import flowork_kernel.utils
import flowork_kernel.utils.payload_helper
import flowork_kernel.ui_shell.components
import flowork_kernel.ui_shell.components.LabelledCombobox
import tkinter.StringVar
import base64
import imaplib
import email
import re
import email.header
import tkinter.BooleanVar
import smtplib
import email.mime
import email.mime.text
import email.mime.multipart
import pandas
import flowork_kernel.exceptions
import tkinter.filedialog
import openpyxl
import openpyxl.load_workbook
import typing
import flowork_kernel.ui_shell.components.PropertyField
import flowork_kernel.ui_shell.components.InfoLabel
import flowork_kernel.ui_shell.components.Separator
import flowork_kernel.utils.condition_evaluator
import PIL
import PIL.Image
import PIL.ImageTk
import threading
import tkinter.Text
import time
import tkinter.IntVar
import tkinter.DoubleVar
import flowork_kernel.utils.file_helper
import shutil
import ntpath