# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from flowork_kernel.api_client import ApiClient
from flowork_kernel.exceptions import MandatoryUpdateRequiredError, PermissionDeniedError
from tkinter import messagebox
from typing import Any
from typing_extensions import Self
import time

class StartupService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def run_startup_sequence(self: Self) -> Any: ...
    def _attempt_auto_login(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import time
import tkinter
import tkinter.messagebox
import flowork_kernel
import flowork_kernel.exceptions
import flowork_kernel.api_client