# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from core.ChatGPTConnection import ChatGPTConnection
from flowork_kernel.api_contract import BaseAIProvider
from typing import Any
from typing_extensions import Self

class ChatGPTProvider(BaseAIProvider):
    def __init__(self: Self, kernel: Any, manifest: dict) -> None: ...
    def get_provider_name(self: Self) -> str: ...
    def is_ready(self: Self) -> tuple[bool, str]: ...
    def generate_response(self: Self, prompt: str) -> dict: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract