# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, IConfigurableUI, IDataPreviewer, IExecutable
from flowork_kernel.ui_shell import shared_properties
from flowork_kernel.ui_shell.components.InfoLabel import InfoLabel
from flowork_kernel.ui_shell.components.LabelledCombobox import LabelledCombobox
from flowork_kernel.utils.payload_helper import get_nested_value
from llama_cpp import Llama
from tkinter import StringVar
from transformers import pipeline
from typing import Any
from typing_extensions import Self
import json
import os
import ttkbootstrap

TRANSFORMERS_AVAILABLE = True
TRANSFORMERS_AVAILABLE = False
LLAMA_CPP_AVAILABLE = True
LLAMA_CPP_AVAILABLE = False
class AICenterModule(BaseModule, IExecutable, IConfigurableUI, IDataPreviewer):
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def _get_all_available_endpoints(self: Self) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import ttkbootstrap
import tkinter
import tkinter.StringVar
import flowork_kernel
import flowork_kernel.api_contract
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.shared_properties
import flowork_kernel.ui_shell.components
import flowork_kernel.ui_shell.components.LabelledCombobox
import flowork_kernel.ui_shell.components.InfoLabel
import flowork_kernel.utils
import flowork_kernel.utils.payload_helper
import json
import transformers
import transformers.pipeline
import llama_cpp
import llama_cpp.Llama
import ntpath
import tkinter.scrolledtext
import base64
import imaplib
import email
import re
import email.header
import tkinter.BooleanVar
import smtplib
import email.mime
import email.mime.text
import email.mime.multipart
import pandas
import flowork_kernel.exceptions
import tkinter.filedialog
import openpyxl
import openpyxl.load_workbook
import typing
import flowork_kernel.ui_shell.components.PropertyField
import flowork_kernel.ui_shell.components.Separator
import flowork_kernel.utils.condition_evaluator
import PIL
import PIL.Image
import PIL.ImageTk
import tkinter.IntVar
import time
import urllib
import urllib.parse
import undetected_chromedriver
import bs4
import bs4.BeautifulSoup
import selenium
import selenium.webdriver
import selenium.webdriver.common
import selenium.webdriver.common.by
import selenium.webdriver.support
import selenium.webdriver.support.ui
import selenium.webdriver.support.expected_conditions
import threading
import flowork_kernel.api_client
import tkinter.Text
import tkinter.DoubleVar
import flowork_kernel.utils.file_helper
import shutil