# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from flowork_kernel.exceptions import PermissionDeniedError
from typing import Any
from typing_extensions import Self
import base64
import json
import logging
import os
import random
import secrets
import string
import threading

class VariableManagerService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def autodiscover_and_sync_variables(self: Self) -> Any: ...
    def load_variables(self: Self) -> Any: ...
    def _save_variables_to_file(self: Self) -> Any: ...
    def get_all_variables_for_api(self: Self) -> Any: ...
    def get_all_variables_for_ui(self: Self) -> Any: ...
    def get_variable(self: Self, name: Any) -> Any: ...
    def set_variable(self: Self, name: Any, value: Any, is_secret: Any, is_enabled: Any, mode: Any) -> Any: ...
    def set_variable_enabled_state(self: Self, name: Any, is_enabled: bool) -> Any: ...
    def delete_variable(self: Self, name: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import json
import threading
import base64
import logging
import secrets
import string
import random
import flowork_kernel
import flowork_kernel.exceptions
import ntpath