# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_client import ApiClient
from tkinter import messagebox
from typing import Any
from typing_extensions import Self
import os
import threading
import ttkbootstrap

class LicenseManagementFrame:
    def __init__(self: Self, parent: Any, kernel: Any) -> None: ...
    def _build_widgets(self: Self) -> Any: ...
    def refresh_content(self: Self) -> Any: ...
    def _deactivate_license_action(self: Self) -> Any: ...
    def _deactivate_worker(self: Self) -> Any: ...
    def _on_deactivate_complete(self: Self, success: Any, message: Any) -> Any: ...
    def load_settings_data(self: Self, settings_data: Any) -> Any: ...
    def get_settings_data(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ttkbootstrap
import tkinter
import tkinter.messagebox
import os
import threading
import flowork_kernel
import flowork_kernel.api_client