# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule
from flowork_kernel.ui_shell.shared_properties import create_debug_and_reliability_ui, create_loop_settings_ui
from tkinter import StringVar
from typing import Any
from typing_extensions import Self
import threading
import ttkbootstrap

class ManualApprovalModule(BaseModule):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def on_approval_response(self: Self, result: str) -> Any: ...
    def get_result(self: Self) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract
import threading
import ttkbootstrap
import tkinter
import tkinter.StringVar
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.shared_properties