# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dotenv import load_dotenv
from typing import Any
from typing_extensions import Self
import os
import ttkbootstrap
import webbrowser

class PricingPage:
    def __init__(self: Self, parent_notebook: Any, kernel_instance: Any) -> None: ...
    def _build_ui(self: Self) -> Any: ...
    def _create_tier_card(self: Self, parent: Any, tier_key: Any, data: Any, is_highlighted: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ttkbootstrap
import webbrowser
import os
import dotenv
import dotenv.load_dotenv
import ntpath