# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self

class BaseService:
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def start(self: Self) -> Any: ...
    def stop(self: Self) -> Any: ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
