# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, BaseUIProvider
from typing import Any
from typing_extensions import Self

class MetricsDashboardModule(BaseModule, BaseUIProvider):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def get_ui_tabs(self: Self) -> Any: ...
    def get_menu_items(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract