# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, BaseUIProvider
from typing import Any
from typing_extensions import Self

class MetricsDashboardModule(BaseModule, BaseUIProvider):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def get_ui_tabs(self: Self) -> Any: ...
    def get_menu_items(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import smtplib
import tempfile
import re
import email
import email.mime
import email.mime.text
import email.mime.multipart
import email.mime.base
import email.encoders
import ttkbootstrap
import tkinter
import tkinter.StringVar
import tkinter.scrolledtext
import flowork_kernel
import flowork_kernel.api_contract
import flowork_kernel.utils
import flowork_kernel.utils.payload_helper
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.components
import flowork_kernel.ui_shell.components.LabelledCombobox
import tkinter.messagebox
import threading
import time
import flowork_kernel.api_client
import widgets
import widgets.dataset_manager_widget
import widgets.dataset_manager_widget.dataset_manager_widget
import ntpath
import _frozen_importlib_external
import pyaudio
import mss
import flowork_kernel.ui_shell.custom_widgets
import flowork_kernel.ui_shell.custom_widgets.tooltip
import tkinter.ttk
import json
import tkinter.Menu
import tkinter.Toplevel
import flowork_kernel.ui_shell.canvas_manager
import plugins.flowork_core_ui.marketplace_page
import plugins.flowork_core_ui.pricing_page
import abc
import tkinter.BooleanVar
import tkinter.Text
import tkinter.filedialog
import uuid
import zipfile
import shutil
import importlib
import inspect
import collections
import collections.OrderedDict
import flowork_kernel.ui_shell.custom_widgets.DualListbox
import base64
import plugins.flowork_core_ui.settings_components.license_management_frame
import flowork_kernel.ui_shell.custom_widgets.scrolled_frame
import flowork_kernel.exceptions
import platform
import subprocess
import datetime
import flowork_kernel.utils.performance_logger
import sys
import plugins.system_diagnostics_plugin.base_scanner
import queue
import ast