# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseDashboardWidget, IDataPreviewer
from flowork_kernel.core import build_security
from tkinter import ttk
from typing import Any
from typing_extensions import Self
import json
import ttkbootstrap

class DataCanvasWidget(BaseDashboardWidget):
    def __init__(self: Self, parent: Any, coordinator_tab: Any, kernel: Any, widget_id: str) -> None: ...
    def sync_with_logic_canvas(self: Self, logic_canvas_nodes: Any) -> Any: ...

_UNUSED_SIGNATURE = 'B3Ba%m#rDeKa'
_UNUSED_SIGNATURE = 'B3Ba%m#rDeKa'

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.core
import flowork_kernel.core.build_security
import ttkbootstrap
import tkinter
import tkinter.ttk
import json
import flowork_kernel.api_contract