# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule
from typing import Any
from typing_extensions import Self
import json
import os
import time

class MetricsLogger(BaseModule):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def on_load(self: Self) -> Any: ...
    def on_metrics_updated(self: Self, metrics_data: Any) -> Any: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import json
import time
import flowork_kernel
import flowork_kernel.api_contract
import ntpath