# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from typing import Any
from typing_extensions import Self
import mss
import numpy
import os
import pyaudio
import shutil
import subprocess
import tempfile
import threading
import time
import wave

class ScreenRecorderService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def start(self: Self) -> Any: ...
    def start_recording(self: Self, monitor_num: Any, record_audio: Any, gain: Any) -> Any: ...
    def stop_recording(self: Self) -> Any: ...
    def _audio_worker(self: Self) -> Any: ...
    def _capture_worker(self: Self, monitor_num: Any) -> Any: ...
    def _merge_with_ffmpeg(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import threading
import time
import shutil
import wave
import pyaudio
import numpy
import mss
import subprocess
import tempfile
import ntpath