# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseModule, EnumVarWrapper, IConfigurableUI, IDataPreviewer, IExecutable
from flowork_kernel.ui_shell.components.InfoLabel import InfoLabel
from flowork_kernel.ui_shell.components.LabelledCombobox import LabelledCombobox
from flowork_kernel.ui_shell.components.PropertyField import PropertyField
from flowork_kernel.ui_shell.components.Separator import Separator
from flowork_kernel.ui_shell.shared_properties import create_debug_and_reliability_ui, create_loop_settings_ui
from flowork_kernel.utils.condition_evaluator import evaluate_condition
from flowork_kernel.utils.payload_helper import get_nested_value
from tkinter import StringVar
from typing import Any
from typing_extensions import Self
import ttkbootstrap

class IfModule(BaseModule, IExecutable, IConfigurableUI, IDataPreviewer):
    def __init__(self: Self, module_id: Any, services: Any) -> None: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.api_contract
import ttkbootstrap
import tkinter
import tkinter.StringVar
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.shared_properties
import flowork_kernel.ui_shell.components
import flowork_kernel.ui_shell.components.LabelledCombobox
import flowork_kernel.ui_shell.components.PropertyField
import flowork_kernel.ui_shell.components.InfoLabel
import flowork_kernel.ui_shell.components.Separator
import flowork_kernel.utils
import flowork_kernel.utils.payload_helper
import flowork_kernel.utils.condition_evaluator