# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseBrainProvider, IConfigurableUI, IDataPreviewer, IExecutable
from flowork_kernel.ui_shell.components.LabelledCombobox import LabelledCombobox
from tkinter import StringVar
from typing import Any
from typing_extensions import Self
import ttkbootstrap

class BrainProviderPlugin(BaseBrainProvider, IExecutable, IConfigurableUI, IDataPreviewer):
    def __init__(self: Self, module_id: str, services: dict) -> None: ...
    def get_provider_name(self: Self) -> str: ...
    def is_ready(self: Self) -> tuple[bool, str]: ...
    def think(self: Self, objective: str, tools_string: str, history: list, last_observation: str) -> dict: ...
    def execute(self: Self, payload: Any, config: Any, status_updater: Any, ui_callback: Any, mode: Any) -> Any: ...
    def create_properties_ui(self: Self, parent_frame: Any, get_current_config: Any, available_vars: Any) -> Any: ...
    def get_data_preview(self: Self, config: dict) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ttkbootstrap
import tkinter
import tkinter.StringVar
import flowork_kernel
import flowork_kernel.api_contract
import flowork_kernel.ui_shell
import flowork_kernel.ui_shell.components
import flowork_kernel.ui_shell.components.LabelledCombobox