# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flowork_kernel.api_contract import BaseTriggerListener
from typing import Any
from typing_extensions import Self
import psutil
import threading
import time

class ProcessListener(BaseTriggerListener):
    def __init__(self: Self, trigger_id: str, config: dict, services: dict) -> None: ...
    def _find_pids_by_name(self: Self) -> Any: ...
    def start(self: Self) -> Any: ...
    def _monitor_process(self: Self) -> Any: ...
    def stop(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import time
import threading
import psutil
import flowork_kernel
import flowork_kernel.api_contract